version: 2
jobs:
  build:
    docker:
      - image: theasp/clojurescript-nodejs:shadow-cljs
    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm run build